export interface Client {
  id: string
  name: string
  aum: number
  status: "Active" | "Onboarding" | "At Risk" | "Review Needed"
  riskScore: number
  investmentModel: string
  custodian: string
  finPlan: "Current" | "Needs Update" | "None" | "Expired" | "In Progress"
  primaryAdvisor: {
    name: string
    initials: string
    color: string
  }
  nextReview: string
  serviceTier: "Silver" | "Gold" | "Platinum" | "Bronze"
  ytdPerf: number
  unrealizedGL: number
  cashPercent: number
}

export const clientData: Client[] = [
  {
    id: "1",
    name: "Andrew & Charles Allen",
    aum: 5083491,
    status: "Active",
    riskScore: 63,
    investmentModel: "Growth Moderate",
    custodian: "Charles Schwab",
    finPlan: "Current",
    primaryAdvisor: { name: "Michael Chen", initials: "MC", color: "bg-teal-500" },
    nextReview: "2024/8/7",
    serviceTier: "Silver",
    ytdPerf: -1.85,
    unrealizedGL: 254615,
    cashPercent: 14,
  },
  {
    id: "2",
    name: "Margaret Rodriguez",
    aum: 4980751,
    status: "Active",
    riskScore: 47,
    investmentModel: "ESG Global",
    custodian: "Charles Schwab",
    finPlan: "Current",
    primaryAdvisor: { name: "Sarah Jenkins", initials: "SJ", color: "bg-amber-500" },
    nextReview: "2024/3/18",
    serviceTier: "Gold",
    ytdPerf: -4.87,
    unrealizedGL: 625729,
    cashPercent: 1,
  },
  {
    id: "3",
    name: "Sandra Gonzalez",
    aum: 4872201,
    status: "Active",
    riskScore: 94,
    investmentModel: "Conservative",
    custodian: "TD Ameritrade",
    finPlan: "Needs Update",
    primaryAdvisor: { name: "Michael Chen", initials: "MC", color: "bg-teal-500" },
    nextReview: "2024/2/3",
    serviceTier: "Gold",
    ytdPerf: -2.74,
    unrealizedGL: -307101,
    cashPercent: 5,
  },
  {
    id: "4",
    name: "King Family Trust",
    aum: 4835750,
    status: "Active",
    riskScore: 77,
    investmentModel: "Conservative",
    custodian: "Interactive Brokers",
    finPlan: "Current",
    primaryAdvisor: { name: "Robert Taylor", initials: "RT", color: "bg-blue-500" },
    nextReview: "2024/2/23",
    serviceTier: "Silver",
    ytdPerf: 5.68,
    unrealizedGL: -1025003,
    cashPercent: 6,
  },
  {
    id: "5",
    name: "Margaret & Steven Baker",
    aum: 4772213,
    status: "Active",
    riskScore: 67,
    investmentModel: "Tech Sector Focus",
    custodian: "Interactive Brokers",
    finPlan: "Current",
    primaryAdvisor: { name: "Michael Chen", initials: "MC", color: "bg-teal-500" },
    nextReview: "2024/8/14",
    serviceTier: "Gold",
    ytdPerf: 7.95,
    unrealizedGL: 923384,
    cashPercent: 6,
  },
  {
    id: "6",
    name: "Williams Family Trust",
    aum: 4768040,
    status: "Active",
    riskScore: 62,
    investmentModel: "Balanced",
    custodian: "Interactive Brokers",
    finPlan: "Needs Update",
    primaryAdvisor: { name: "David Wilson", initials: "DW", color: "bg-indigo-500" },
    nextReview: "2024/2/21",
    serviceTier: "Gold",
    ytdPerf: 2.46,
    unrealizedGL: -944742,
    cashPercent: 5,
  },
  {
    id: "7",
    name: "Robert & Kenneth Roberts",
    aum: 4689010,
    status: "Active",
    riskScore: 14,
    investmentModel: "Income Focused",
    custodian: "Pershing",
    finPlan: "None",
    primaryAdvisor: { name: "Jennifer Wu", initials: "JW", color: "bg-purple-500" },
    nextReview: "2024/4/27",
    serviceTier: "Platinum",
    ytdPerf: 1.56,
    unrealizedGL: -553881,
    cashPercent: 12,
  },
  {
    id: "8",
    name: "Susan Allen",
    aum: 4635222,
    status: "Onboarding",
    riskScore: 58,
    investmentModel: "Tech Sector Focus",
    custodian: "Pershing",
    finPlan: "Expired",
    primaryAdvisor: { name: "Jennifer Wu", initials: "JW", color: "bg-purple-500" },
    nextReview: "2024/2/15",
    serviceTier: "Silver",
    ytdPerf: 4.14,
    unrealizedGL: 1568118,
    cashPercent: 9,
  },
  {
    id: "9",
    name: "William Garcia",
    aum: 4607885,
    status: "Onboarding",
    riskScore: 14,
    investmentModel: "Conservative",
    custodian: "TD Ameritrade",
    finPlan: "None",
    primaryAdvisor: { name: "Robert Taylor", initials: "RT", color: "bg-blue-500" },
    nextReview: "2024/4/25",
    serviceTier: "Bronze",
    ytdPerf: 8.60,
    unrealizedGL: 787932,
    cashPercent: 7,
  },
  {
    id: "10",
    name: "David Davis",
    aum: 4547421,
    status: "At Risk",
    riskScore: 82,
    investmentModel: "Tech Sector Focus",
    custodian: "TD Ameritrade",
    finPlan: "Current",
    primaryAdvisor: { name: "David Wilson", initials: "DW", color: "bg-indigo-500" },
    nextReview: "2024/3/5",
    serviceTier: "Platinum",
    ytdPerf: 6.05,
    unrealizedGL: 163871,
    cashPercent: 1,
  },
  {
    id: "11",
    name: "David Hernandez",
    aum: 4520380,
    status: "At Risk",
    riskScore: 47,
    investmentModel: "Conservative",
    custodian: "Interactive Brokers",
    finPlan: "Needs Update",
    primaryAdvisor: { name: "Sarah Jenkins", initials: "SJ", color: "bg-amber-500" },
    nextReview: "2024/10/7",
    serviceTier: "Silver",
    ytdPerf: -3.72,
    unrealizedGL: -1300215,
    cashPercent: 2,
  },
  {
    id: "12",
    name: "Anthony Gonzalez",
    aum: 4497827,
    status: "At Risk",
    riskScore: 12,
    investmentModel: "Income Focused",
    custodian: "Charles Schwab",
    finPlan: "Needs Update",
    primaryAdvisor: { name: "David Wilson", initials: "DW", color: "bg-indigo-500" },
    nextReview: "2024/2/7",
    serviceTier: "Gold",
    ytdPerf: -0.76,
    unrealizedGL: 374998,
    cashPercent: 4,
  },
  {
    id: "13",
    name: "Davis Family Trust",
    aum: 4417724,
    status: "Active",
    riskScore: 54,
    investmentModel: "Conservative",
    custodian: "Interactive Brokers",
    finPlan: "Needs Update",
    primaryAdvisor: { name: "Sarah Jenkins", initials: "SJ", color: "bg-amber-500" },
    nextReview: "2024/2/22",
    serviceTier: "Gold",
    ytdPerf: 0.88,
    unrealizedGL: -1477709,
    cashPercent: 8,
  },
  {
    id: "14",
    name: "Robert Wright",
    aum: 4288096,
    status: "Onboarding",
    riskScore: 96,
    investmentModel: "Income Focused",
    custodian: "Pershing",
    finPlan: "Current",
    primaryAdvisor: { name: "Michael Chen", initials: "MC", color: "bg-teal-500" },
    nextReview: "2024/11/27",
    serviceTier: "Platinum",
    ytdPerf: -1.30,
    unrealizedGL: 1607791,
    cashPercent: 3,
  },
  {
    id: "15",
    name: "Donald Perez",
    aum: 4045555,
    status: "Review Needed",
    riskScore: 69,
    investmentModel: "Tech Sector Focus",
    custodian: "Charles Schwab",
    finPlan: "Current",
    primaryAdvisor: { name: "David Wilson", initials: "DW", color: "bg-indigo-500" },
    nextReview: "2024/5/5",
    serviceTier: "Bronze",
    ytdPerf: 13.63,
    unrealizedGL: -822070,
    cashPercent: 15,
  },
  {
    id: "16",
    name: "Christopher Gonzalez",
    aum: 3834527,
    status: "Active",
    riskScore: 37,
    investmentModel: "ESG Global",
    custodian: "Interactive Brokers",
    finPlan: "Expired",
    primaryAdvisor: { name: "Robert Taylor", initials: "RT", color: "bg-blue-500" },
    nextReview: "2024/8/23",
    serviceTier: "Platinum",
    ytdPerf: 3.73,
    unrealizedGL: -241090,
    cashPercent: 7,
  },
  {
    id: "17",
    name: "Thomas & Paul Turner",
    aum: 3816777,
    status: "Review Needed",
    riskScore: 28,
    investmentModel: "ESG Global",
    custodian: "Fidelity",
    finPlan: "In Progress",
    primaryAdvisor: { name: "Sarah Jenkins", initials: "SJ", color: "bg-amber-500" },
    nextReview: "2024/9/20",
    serviceTier: "Platinum",
    ytdPerf: 4.20,
    unrealizedGL: 380878,
    cashPercent: 7,
  },
]

export function formatCurrency(value: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value)
}

export function formatCurrencyWithSign(value: number): string {
  const prefix = value >= 0 ? "+" : ""
  return prefix + formatCurrency(value)
}

export function formatPercent(value: number): string {
  const prefix = value >= 0 ? "+" : ""
  return prefix + value.toFixed(2) + "%"
}
